=== YasperFa/MolSim/src/IO/Input/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="output" type="OutputType"/>
                <xs:element name="calculator" type="CalculatorType" />
                <xs:element name="parameters" type="ParametersType"/>
                <xs:element name="cuboids" type="CuboidType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="OutputType">
        <xs:sequence>
            <xs:element name="baseName" type="xs:string" minOccurs="0"/>
            <xs:element name="writeFrequency" type="xs:int" minOccurs="0" default="10"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CalculatorType">
        <xs:sequence>
            <xs:element name="calculatorForce" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ParametersType">
        <xs:sequence>
            <xs:element name="tEnd" type="xs:double" minOccurs="0"/>
            <xs:element name="deltaT" type="xs:double" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CuboidType">
        <xs:sequence>
            <xs:element name="position" type="PositionType"/>
            <xs:element name="dimensions" type="DimensionsType"/>
            <xs:element name="initialVelocity" type="VelocityType"/>
            <xs:element name="distance" type="xs:double"/>
            <xs:element name="meanVelocity" type="xs:double"/>
            <xs:element name="mass" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PositionType">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DimensionsType">
        <xs:sequence>
            <xs:element name="x" type="xs:int"/>
            <xs:element name="y" type="xs:int"/>
            <xs:element name="z" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VelocityType">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== YasperFa/MolSim/input/schemaTest1.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/IO/Input/schema.xsd">
    <output>
        <baseName>XYZ</baseName>
        <writeFrequency>10</writeFrequency>
    </output>
    <calculator>
        <calculatorForce>LJC</calculatorForce>
    </calculator>
    <parameters>
        <tEnd>3.0</tEnd>
        <deltaT>0.0001</deltaT>
    </parameters>
    <shapes>
        <particle>
            <position>
                <x>1.0</x>
                <y>2.0</y>
                <z>3.0</z>
            </position>
            <velocity>
                <x>0.0</x>
                <y>1.0</y>
                <z>0.0</z>
            </velocity>
            <mass>5.0</mass>
        </particle>
    </shapes>
</simulation>

=== YasperFa/MolSim/input/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/IO/Input/schema.xsd">
    <output>
        <baseName>XYZ</baseName>
        <writeFrequency>1</writeFrequency>
    </output>
    <calculator>
         <calculatorForce>Default</calculatorForce>
    </calculator>
    <parameters>
        <tEnd>0.1</tEnd>
        <deltaT>0.0003</deltaT>
    </parameters>
    <cuboids>
        <position>
            <x>0.0</x>
            <y>1.0</y>
            <z>0.0</z>
        </position>
        <dimensions>
            <x>2</x>
            <y>1</y>
            <z>1</z>
        </dimensions>
        <initialVelocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </initialVelocity>
        <distance>1.0</distance>
        <meanVelocity>0.0</meanVelocity>
        <mass>1.0</mass>
    </cuboids>
    <cuboids>
        <position>
            <x>10.0</x>
            <y>1.0</y>
            <z>0.0</z>
        </position>
        <dimensions>
            <x>2</x>
            <y>1</y>
            <z>1</z>
        </dimensions>
        <initialVelocity>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </initialVelocity>
        <distance>1.0</distance>
        <meanVelocity>0.0</meanVelocity>
        <mass>1.0</mass>
    </cuboids>
</simulation>
